[2023-09-20T12:41:29.072+0530] {processor.py:157} INFO - Started process (PID=13292) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:41:29.073+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py for tasks to queue
[2023-09-20T12:41:29.079+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:41:29.078+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:41:29.373+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:41:29.372+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_roadster.sql
[2023-09-20T12:41:29.377+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_roadster_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:41:29.531+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:41:29.531+0530] {manager.py:499} INFO - Created Permission View: %s
[2023-09-20T12:41:29.550+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:41:29.549+0530] {manager.py:499} INFO - Created Permission View: %s
[2023-09-20T12:41:29.564+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:41:29.564+0530] {manager.py:499} INFO - Created Permission View: %s
[2023-09-20T12:41:29.565+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:41:29.565+0530] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:spacex_roadster_pipeline' as access control is unset.
[2023-09-20T12:41:29.566+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:41:29.565+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:41:29.588+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:41:29.587+0530] {dag.py:2937} INFO - Creating ORM DAG for spacex_roadster_pipeline
[2023-09-20T12:41:29.603+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:41:29.603+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_roadster_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:41:29.643+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py took 0.577 seconds
[2023-09-20T12:42:00.090+0530] {processor.py:157} INFO - Started process (PID=13311) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:42:00.091+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py for tasks to queue
[2023-09-20T12:42:00.095+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:42:00.094+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:42:00.382+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:42:00.381+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_roadster.sql
[2023-09-20T12:42:00.387+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_roadster_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:42:00.413+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:42:00.412+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:42:00.441+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:42:00.441+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_roadster_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:42:00.471+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py took 0.386 seconds
[2023-09-20T12:42:30.851+0530] {processor.py:157} INFO - Started process (PID=13425) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:42:30.852+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py for tasks to queue
[2023-09-20T12:42:30.857+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:42:30.856+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:42:30.964+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:42:30.963+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_roadster.sql
[2023-09-20T12:42:30.976+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_roadster_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:42:31.075+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:42:31.073+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:42:31.137+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:42:31.137+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_roadster_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:42:31.190+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py took 0.344 seconds
[2023-09-20T12:43:01.567+0530] {processor.py:157} INFO - Started process (PID=13578) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:43:01.568+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py for tasks to queue
[2023-09-20T12:43:01.572+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:43:01.572+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:43:01.709+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:43:01.707+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_roadster.sql
[2023-09-20T12:43:01.714+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_roadster_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:43:01.744+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:43:01.743+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:43:01.777+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:43:01.777+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_roadster_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:43:01.806+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py took 0.244 seconds
[2023-09-20T12:43:32.047+0530] {processor.py:157} INFO - Started process (PID=13607) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:43:32.049+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py for tasks to queue
[2023-09-20T12:43:32.054+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:43:32.053+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:43:32.151+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:43:32.150+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_roadster.sql
[2023-09-20T12:43:32.156+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_roadster_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:43:32.189+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:43:32.188+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:43:32.219+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:43:32.219+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_roadster_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:43:32.249+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py took 0.208 seconds
[2023-09-20T12:44:02.431+0530] {processor.py:157} INFO - Started process (PID=13638) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:44:02.432+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py for tasks to queue
[2023-09-20T12:44:02.437+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:44:02.436+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:44:02.536+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:44:02.535+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_roadster.sql
[2023-09-20T12:44:02.541+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_roadster_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:44:02.575+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:44:02.574+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:44:02.607+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:44:02.607+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_roadster_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:44:02.641+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py took 0.216 seconds
[2023-09-20T12:44:32.831+0530] {processor.py:157} INFO - Started process (PID=13670) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:44:32.832+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py for tasks to queue
[2023-09-20T12:44:32.836+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:44:32.836+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:44:32.952+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:44:32.951+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_roadster.sql
[2023-09-20T12:44:32.957+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_roadster_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:44:32.989+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:44:32.988+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:44:33.024+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:44:33.024+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_roadster_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:44:33.053+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py took 0.228 seconds
[2023-09-20T12:45:03.314+0530] {processor.py:157} INFO - Started process (PID=13708) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:45:03.316+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py for tasks to queue
[2023-09-20T12:45:03.322+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:45:03.321+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:45:03.420+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:45:03.419+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_roadster.sql
[2023-09-20T12:45:03.426+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_roadster_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:45:03.459+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:45:03.458+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:45:03.505+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:45:03.505+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_roadster_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:45:03.545+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py took 0.236 seconds
[2023-09-20T12:45:33.773+0530] {processor.py:157} INFO - Started process (PID=13748) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:45:33.777+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py for tasks to queue
[2023-09-20T12:45:33.782+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:45:33.782+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:45:33.896+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:45:33.895+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_roadster.sql
[2023-09-20T12:45:33.902+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_roadster_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:45:33.936+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:45:33.935+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:45:33.981+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:45:33.981+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_roadster_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:45:34.018+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py took 0.250 seconds
[2023-09-20T12:46:04.195+0530] {processor.py:157} INFO - Started process (PID=13786) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:46:04.196+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py for tasks to queue
[2023-09-20T12:46:04.200+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:46:04.199+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:46:04.303+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:46:04.301+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_roadster.sql
[2023-09-20T12:46:04.314+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_roadster_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:46:04.364+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:46:04.363+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:46:04.398+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:46:04.398+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_roadster_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:46:04.427+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py took 0.239 seconds
[2023-09-20T12:46:34.546+0530] {processor.py:157} INFO - Started process (PID=13822) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:46:34.547+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py for tasks to queue
[2023-09-20T12:46:34.552+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:46:34.551+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:46:34.647+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:46:34.646+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_roadster.sql
[2023-09-20T12:46:34.653+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_roadster_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:46:34.682+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:46:34.681+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:46:34.712+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:46:34.712+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_roadster_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:46:34.742+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py took 0.202 seconds
[2023-09-20T12:47:05.210+0530] {processor.py:157} INFO - Started process (PID=13851) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:47:05.212+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py for tasks to queue
[2023-09-20T12:47:05.217+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:47:05.216+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:47:05.312+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:47:05.311+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_roadster.sql
[2023-09-20T12:47:05.318+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_roadster_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:47:05.349+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:47:05.349+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:47:05.383+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:47:05.383+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_roadster_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:47:05.412+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py took 0.208 seconds
[2023-09-20T12:47:35.819+0530] {processor.py:157} INFO - Started process (PID=13891) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:47:35.821+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py for tasks to queue
[2023-09-20T12:47:35.826+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:47:35.826+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:47:35.931+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:47:35.930+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_roadster.sql
[2023-09-20T12:47:35.939+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_roadster_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:47:35.986+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:47:35.985+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:47:36.031+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:47:36.031+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_roadster_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:47:36.068+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py took 0.255 seconds
[2023-09-20T12:48:06.160+0530] {processor.py:157} INFO - Started process (PID=13922) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:48:06.162+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py for tasks to queue
[2023-09-20T12:48:06.168+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:48:06.167+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:48:06.309+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:48:06.307+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_roadster.sql
[2023-09-20T12:48:06.315+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_roadster_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py
[2023-09-20T12:48:06.360+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:48:06.359+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:48:06.406+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:48:06.405+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_roadster_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:48:06.453+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_roadster.py took 0.301 seconds
